server:
 port: 8222




spring:
 application:
   name: demo-springcloud-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/

endpoints:
  health:
    enabled: true
    path: /health
zuul:
  routes:
    demo-springcloud-client:  /demo/**
  ignored-services: '*'
  ignore-local-service: true


ribbon:
  eureka:
    enabled: false

#eureka:
#  instance:
#    metadata-map:
#      management.port: ${management.port}

