server:
 port: 8333




spring:
 application:
   name: demo-springcloud-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8555/eureka/

endpoints:
  health:
    enabled: true
    path: /health

#eureka:
#  instance:
#    metadata-map:
#      management.port: ${management.port}

